// AUTO-GENERATED by scripts/sync-public-asset-versions.mjs — do not edit.
export const PUBLIC_ASSET_VERSIONS = {
  "hero-bg.jpg": "1783795324294"
} as const;

export function publicAssetUrl(path: string): string {
  const filename = path.split("/").pop() ?? path;
  const version =
    PUBLIC_ASSET_VERSIONS[filename as keyof typeof PUBLIC_ASSET_VERSIONS];
  return version ? `${path}?v=${version}` : path;
}
